// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: api/news/news.proto

package news

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据ID获取新闻详情请求
type GetNewsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsByIdRequest) Reset() {
	*x = GetNewsByIdRequest{}
	mi := &file_api_news_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsByIdRequest) ProtoMessage() {}

func (x *GetNewsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_news_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsByIdRequest.ProtoReflect.Descriptor instead.
func (*GetNewsByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_news_news_proto_rawDescGZIP(), []int{0}
}

func (x *GetNewsByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 根据ID获取新闻详情响应
type GetNewsByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          *News                  `protobuf:"bytes,1,opt,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsByIdResponse) Reset() {
	*x = GetNewsByIdResponse{}
	mi := &file_api_news_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsByIdResponse) ProtoMessage() {}

func (x *GetNewsByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_news_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsByIdResponse.ProtoReflect.Descriptor instead.
func (*GetNewsByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_news_news_proto_rawDescGZIP(), []int{1}
}

func (x *GetNewsByIdResponse) GetNews() *News {
	if x != nil {
		return x.News
	}
	return nil
}

// 创建新闻请求
type CreateNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewsRequest) Reset() {
	*x = CreateNewsRequest{}
	mi := &file_api_news_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewsRequest) ProtoMessage() {}

func (x *CreateNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_news_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewsRequest.ProtoReflect.Descriptor instead.
func (*CreateNewsRequest) Descriptor() ([]byte, []int) {
	return file_api_news_news_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNewsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNewsRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 创建新闻响应
type CreateNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewsResponse) Reset() {
	*x = CreateNewsResponse{}
	mi := &file_api_news_news_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewsResponse) ProtoMessage() {}

func (x *CreateNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_news_news_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewsResponse.ProtoReflect.Descriptor instead.
func (*CreateNewsResponse) Descriptor() ([]byte, []int) {
	return file_api_news_news_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNewsResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 新闻信息
type News struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime    string                 `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *News) Reset() {
	*x = News{}
	mi := &file_api_news_news_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *News) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*News) ProtoMessage() {}

func (x *News) ProtoReflect() protoreflect.Message {
	mi := &file_api_news_news_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use News.ProtoReflect.Descriptor instead.
func (*News) Descriptor() ([]byte, []int) {
	return file_api_news_news_proto_rawDescGZIP(), []int{4}
}

func (x *News) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *News) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *News) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *News) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

var File_api_news_news_proto protoreflect.FileDescriptor

const file_api_news_news_proto_rawDesc = "" +
	"\n" +
	"\x13api/news/news.proto\x12\x04demo\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\x12GetNewsByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"5\n" +
	"\x13GetNewsByIdResponse\x12\x1e\n" +
	"\x04news\x18\x01 \x01(\v2\n" +
	".demo.NewsR\x04news\"C\n" +
	"\x11CreateNewsRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"$\n" +
	"\x12CreateNewsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"g\n" +
	"\x04News\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\tR\n" +
	"createTime2\xb8\x01\n" +
	"\vNewsService\x12V\n" +
	"\vGetNewsById\x12\x18.demo.GetNewsByIdRequest\x1a\x19.demo.GetNewsByIdResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/news/{id}\x12Q\n" +
	"\n" +
	"CreateNews\x12\x17.demo.CreateNewsRequest\x1a\x18.demo.CreateNewsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/newsB\x11P\x01Z\rdemo/api/newsb\x06proto3"

var (
	file_api_news_news_proto_rawDescOnce sync.Once
	file_api_news_news_proto_rawDescData []byte
)

func file_api_news_news_proto_rawDescGZIP() []byte {
	file_api_news_news_proto_rawDescOnce.Do(func() {
		file_api_news_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_news_news_proto_rawDesc), len(file_api_news_news_proto_rawDesc)))
	})
	return file_api_news_news_proto_rawDescData
}

var file_api_news_news_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_news_news_proto_goTypes = []any{
	(*GetNewsByIdRequest)(nil),  // 0: demo.GetNewsByIdRequest
	(*GetNewsByIdResponse)(nil), // 1: demo.GetNewsByIdResponse
	(*CreateNewsRequest)(nil),   // 2: demo.CreateNewsRequest
	(*CreateNewsResponse)(nil),  // 3: demo.CreateNewsResponse
	(*News)(nil),                // 4: demo.News
}
var file_api_news_news_proto_depIdxs = []int32{
	4, // 0: demo.GetNewsByIdResponse.news:type_name -> demo.News
	0, // 1: demo.NewsService.GetNewsById:input_type -> demo.GetNewsByIdRequest
	2, // 2: demo.NewsService.CreateNews:input_type -> demo.CreateNewsRequest
	1, // 3: demo.NewsService.GetNewsById:output_type -> demo.GetNewsByIdResponse
	3, // 4: demo.NewsService.CreateNews:output_type -> demo.CreateNewsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_news_news_proto_init() }
func file_api_news_news_proto_init() {
	if File_api_news_news_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_news_news_proto_rawDesc), len(file_api_news_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_news_news_proto_goTypes,
		DependencyIndexes: file_api_news_news_proto_depIdxs,
		MessageInfos:      file_api_news_news_proto_msgTypes,
	}.Build()
	File_api_news_news_proto = out.File
	file_api_news_news_proto_goTypes = nil
	file_api_news_news_proto_depIdxs = nil
}
